import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Language = 'en' | 'vi';

type Variables = Record<string, string | number>;

interface LanguageContextValue {
  language: Language;
  locale: string;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (text: string, variables?: Variables) => string;
}

const VI: Record<string, string> = {
  Dashboard: 'Tổng quan',
  Devices: 'Thiết bị',
  Topology: 'Cấu trúc mạng',
  'MQTT Logs': 'Nhật ký MQTT',
  Alerts: 'Cảnh báo',
  Coordinator: 'Bộ điều phối',
  Settings: 'Cài đặt',
  Live: 'Trực tuyến',
  Offline: 'Ngoại tuyến',
  Online: 'Trực tuyến',
  Guest: 'Khách',
  'Sign out': 'Đăng xuất',
  'IoT Platform': 'Nền tảng IoT',
  'Switch to light mode': 'Chuyển sang giao diện sáng',
  'Switch to dark mode': 'Chuyển sang giao diện tối',
  Light: 'Sáng',
  Dark: 'Tối',
  Language: 'Ngôn ngữ',
  English: 'Tiếng Anh',
  Vietnamese: 'Tiếng Việt',
  'Choose the language used throughout the interface': 'Chọn ngôn ngữ sử dụng trong toàn bộ giao diện',
  'Sign in to the IoT monitoring platform': 'Đăng nhập vào nền tảng giám sát IoT',
  Email: 'Email',
  Password: 'Mật khẩu',
  'Sign in': 'Đăng nhập',
  'Default credentials: admin@local / admin123': 'Tài khoản mặc định: admin@local / admin123',
  'Live overview of your Zigbee network': 'Tổng quan trực tiếp về mạng Zigbee của bạn',
  'Dashboard unavailable': 'Không thể tải tổng quan',
  'Is the NestJS backend running and connected to PostgreSQL?': 'Backend NestJS đã chạy và kết nối PostgreSQL chưa?',
  'Total Devices': 'Tổng thiết bị',
  'Permit join OPEN': 'Cho phép ghép nối đang MỞ',
  Connected: 'Đã kết nối',
  Down: 'Mất kết nối',
  'Network Health': 'Sức khỏe mạng',
  'Low Battery': 'Pin yếu',
  'Active Alerts': 'Cảnh báo đang hoạt động',
  'Battery Devices': 'Thiết bị dùng pin',
  'Latest Sensor Readings': 'Dữ liệu cảm biến mới nhất',
  'Online devices with a recent payload': 'Thiết bị trực tuyến có dữ liệu gần đây',
  'View all': 'Xem tất cả',
  'No readings yet': 'Chưa có dữ liệu',
  'Pair a device and open permit join to start receiving data.': 'Ghép nối thiết bị và mở cho phép tham gia để bắt đầu nhận dữ liệu.',
  'Unknown model': 'Không rõ mẫu',
  'Recent Events': 'Sự kiện gần đây',
  'Joins, leaves, interviews and bridge logs': 'Tham gia, rời mạng, phỏng vấn và nhật ký bridge',
  'No events yet': 'Chưa có sự kiện',
  'discovered on the Zigbee network': 'được phát hiện trên mạng Zigbee',
  'Search by name, model, manufacturer or IEEE…': 'Tìm theo tên, mẫu, nhà sản xuất hoặc IEEE…',
  'All types': 'Tất cả loại',
  Routers: 'Bộ định tuyến',
  'End devices': 'Thiết bị đầu cuối',
  'Online only': 'Chỉ trực tuyến',
  'No devices found': 'Không tìm thấy thiết bị',
  'Open permit join on the Coordinator page and put your device into pairing mode.': 'Mở cho phép tham gia tại trang Bộ điều phối và đưa thiết bị vào chế độ ghép nối.',
  Unknown: 'Không rõ',
  'Awaiting pair': 'Chờ ghép nối',
  seen: 'đã thấy',
  ON: 'BẬT',
  OFF: 'TẮT',
  'click to toggle': 'nhấn để chuyển',
  'Theme, language, alert thresholds, MQTT identity and OTA job history': 'Giao diện, ngôn ngữ, ngưỡng cảnh báo, định danh MQTT và lịch sử OTA',
  Appearance: 'Giao diện',
  'Light and dark backgrounds for the monitoring UI': 'Nền sáng và tối cho giao diện giám sát',
  'Alert Thresholds': 'Ngưỡng cảnh báo',
  'Low battery percent': 'Phần trăm pin yếu',
  'High temperature (°C)': 'Nhiệt độ cao (°C)',
  'Save thresholds': 'Lưu ngưỡng',
  'Thresholds updated for this process': 'Đã cập nhật ngưỡng cho tiến trình này',
  Platform: 'Nền tảng',
  Version: 'Phiên bản',
  'Base topic': 'Topic gốc',
  Auth: 'Xác thực',
  Enabled: 'Bật',
  Disabled: 'Tắt',
  'History retention': 'Thời gian lưu lịch sử',
  'MQTT log retention': 'Thời gian lưu nhật ký MQTT',
  'Offline timeout': 'Thời gian chờ ngoại tuyến',
  days: 'ngày',
  hours: 'giờ',
  minutes: 'phút',
  'OTA Jobs': 'Tác vụ OTA',
  'Firmware update history': 'Lịch sử cập nhật firmware',
  'No OTA jobs yet': 'Chưa có tác vụ OTA',
  Device: 'Thiết bị',
  Status: 'Trạng thái',
  Progress: 'Tiến độ',
  Versions: 'Phiên bản',
  Started: 'Bắt đầu',
  'Back to devices': 'Quay lại thiết bị',
  'Device not found': 'Không tìm thấy thiết bị',
  'It may have left the network. Return to the device list.': 'Thiết bị có thể đã rời mạng. Hãy quay lại danh sách thiết bị.',
  Identify: 'Nhận diện',
  Ping: 'Ping',
  Reconfigure: 'Cấu hình lại',
  Remove: 'Xóa',
  'Command sent': 'Đã gửi lệnh',
  'No image': 'Không có ảnh',
  'General Information': 'Thông tin chung',
  'Friendly Name': 'Tên thân thiện',
  'IEEE Address': 'Địa chỉ IEEE',
  'Network Address': 'Địa chỉ mạng',
  Manufacturer: 'Nhà sản xuất',
  Model: 'Mẫu',
  'Power Source': 'Nguồn điện',
  Interview: 'Phỏng vấn',
  'Last Seen': 'Thấy lần cuối',
  'Link Quality': 'Chất lượng liên kết',
  Battery: 'Pin',
  Firmware: 'Firmware',
  Description: 'Mô tả',
  Rename: 'Đổi tên',
  'New friendly name': 'Tên thân thiện mới',
  'Current values': 'Giá trị hiện tại',
  'Sensors and controls from Zigbee2MQTT expose metadata': 'Cảm biến và điều khiển từ metadata expose của Zigbee2MQTT',
  'Bridge status': 'Trạng thái bridge',
  'Historical Data': 'Dữ liệu lịch sử',
  'Selectable ranges with bucketed time series': 'Khoảng thời gian có thể chọn với chuỗi thời gian',
  'Last Hour': 'Giờ vừa qua',
  Today: 'Hôm nay',
  'Last 24 Hours': '24 giờ qua',
  'Last 7 Days': '7 ngày qua',
  'Last 30 Days': '30 ngày qua',
  'No chartable history yet': 'Chưa có lịch sử để vẽ biểu đồ',
  'Numeric readings will appear here.': 'Dữ liệu số sẽ xuất hiện tại đây.',
  'Supported Exposes': 'Expose được hỗ trợ',
  properties: 'thuộc tính',
  Property: 'Thuộc tính',
  Type: 'Loại',
  Access: 'Quyền',
  Unit: 'Đơn vị',
  'Raw MQTT Payload': 'Payload MQTT thô',
  'Last state message': 'Thông điệp trạng thái mới nhất',
  'Device Attributes': 'Thuộc tính thiết bị',
  'Latest value per property': 'Giá trị mới nhất cho mỗi thuộc tính',
  Value: 'Giá trị',
  Updated: 'Đã cập nhật',
  'OTA Firmware': 'Firmware OTA',
  'Supported by this device': 'Thiết bị này hỗ trợ',
  'Not advertised': 'Không được công bố',
  Check: 'Kiểm tra',
  Update: 'Cập nhật',
  'Current build': 'Bản dựng hiện tại',
  unknown: 'không rõ',
  'View OTA jobs in settings →': 'Xem tác vụ OTA trong cài đặt →',
  'Network Topology': 'Cấu trúc mạng',
  'Coordinator, routers, end devices and parent-child link quality': 'Bộ điều phối, bộ định tuyến, thiết bị đầu cuối và chất lượng liên kết',
  'Scan network': 'Quét mạng',
  'No topology snapshot yet': 'Chưa có ảnh chụp cấu trúc mạng',
  'Click “Scan network” to walk every router neighbour table through Zigbee2MQTT. This can take a minute.': 'Nhấn “Quét mạng” để đọc bảng láng giềng của mọi bộ định tuyến qua Zigbee2MQTT. Việc này có thể mất một phút.',
  Coordinators: 'Bộ điều phối',
  'End Devices': 'Thiết bị đầu cuối',
  Links: 'Liên kết',
  weak: 'yếu',
  'Last scan': 'Lần quét cuối',
  'Auto-refreshes when a new snapshot arrives over WebSocket': 'Tự làm mới khi có ảnh chụp mới qua WebSocket',
  'Node details': 'Chi tiết nút',
  'Scan failed': 'Quét thất bại',
  'Last seen': 'Thấy lần cuối',
  'Select a node': 'Chọn một nút',
  'Live traffic between Zigbee2MQTT, Mosquitto and the backend': 'Lưu lượng trực tiếp giữa Zigbee2MQTT, Mosquitto và backend',
  'Show history': 'Xem lịch sử',
  'Show live': 'Xem trực tiếp',
  Resume: 'Tiếp tục',
  Pause: 'Tạm dừng',
  'Export JSON': 'Xuất JSON',
  Clear: 'Xóa',
  'Delete all stored MQTT logs?': 'Xóa toàn bộ nhật ký MQTT đã lưu?',
  'Search topic or payload…': 'Tìm topic hoặc payload…',
  'Filter topic…': 'Lọc topic…',
  'All directions': 'Mọi hướng',
  Inbound: 'Đi vào',
  Outbound: 'Đi ra',
  Timestamp: 'Thời gian',
  Topic: 'Topic',
  Direction: 'Hướng',
  'Payload / Device': 'Payload / Thiết bị',
  'No messages': 'Không có thông điệp',
  'Waiting for MQTT traffic…': 'Đang chờ lưu lượng MQTT…',
  'Nothing matched the current filters.': 'Không có dữ liệu khớp bộ lọc hiện tại.',
  'Low battery, offline devices, water leak, smoke and more': 'Pin yếu, thiết bị ngoại tuyến, rò nước, khói và nhiều hơn',
  'Acknowledge all': 'Xác nhận tất cả',
  Active: 'Đang hoạt động',
  Critical: 'Nghiêm trọng',
  Warning: 'Cảnh báo',
  Unacknowledged: 'Chưa xác nhận',
  'No alerts': 'Không có cảnh báo',
  'Everything looks calm.': 'Mọi thứ đều ổn.',
  resolved: 'đã xử lý',
  new: 'mới',
  System: 'Hệ thống',
  last: 'lần cuối',
  Acknowledge: 'Xác nhận',
  Resolve: 'Xử lý',
  'USB Zigbee coordinator detection and network settings': 'Phát hiện bộ điều phối Zigbee USB và cài đặt mạng',
  'Disable Permit Join': 'Tắt cho phép tham gia',
  'Enable Permit Join': 'Bật cho phép tham gia',
  'Restart bridge': 'Khởi động lại bridge',
  Bridge: 'Bridge',
  'Permit Join': 'Cho phép tham gia',
  Open: 'Mở',
  Closed: 'Đóng',
  'Pairing mode': 'Chế độ ghép nối',
  Auto: 'Tự động',
  Manual: 'Thủ công',
  Channel: 'Kênh',
  'Device discovery': 'Phát hiện thiết bị',
  'Auto-pair (nearby)': 'Tự động ghép nối (gần)',
  'Manual sync': 'Đồng bộ thủ công',
  'Sync window (seconds)': 'Thời gian đồng bộ (giây)',
  'Run Manual Sync': 'Chạy đồng bộ thủ công',
  'Coordinator Information': 'Thông tin bộ điều phối',
  'Restart required': 'Cần khởi động lại',
  Yes: 'Có',
  No: 'Không',
  'Detected USB Ports': 'Cổng USB được phát hiện',
  Rescan: 'Quét lại',
  'No serial ports found': 'Không tìm thấy cổng serial',
  'Unknown device': 'Thiết bị không rõ',
  Other: 'Khác',
  Use: 'Sử dụng',
  Configuration: 'Cấu hình',
  'Serial Port': 'Cổng serial',
  'Baud Rate': 'Tốc độ baud',
  Adapter: 'Bộ chuyển đổi',
  'Extended PAN ID': 'PAN ID mở rộng',
  'Network Key': 'Khóa mạng',
  'Log Level': 'Mức nhật ký',
  'Save settings': 'Lưu cài đặt',
  Saved: 'Đã lưu',
  'Nearby Zigbee device': 'Thiết bị Zigbee ở gần',
  'Pair it with this coordinator?': 'Ghép nối với bộ điều phối này?',
  'Ask again later': 'Hỏi lại sau',
  'Near coordinator': 'Gần bộ điều phối',
  'In radio range': 'Trong phạm vi sóng',
  Seen: 'Đã thấy',
  'Don’t pair': 'Không ghép nối',
  Pair: 'Ghép nối',
  'No exposes reported yet. Wait for the device interview to complete.': 'Chưa có expose nào. Hãy chờ quá trình phỏng vấn thiết bị hoàn tất.',
  Config: 'Cấu hình',
  settings: 'cài đặt',
  'Toggle {property}': 'Chuyển {property}',
  'Select…': 'Chọn…',
  Set: 'Đặt',
  Excellent: 'Xuất sắc',
  Good: 'Tốt',
  Fair: 'Trung bình',
  Weak: 'Yếu',
  never: 'chưa bao giờ',
};

function translate(language: Language, text: string, variables?: Variables): string {
  const template = language === 'vi' ? VI[text] ?? text : text;
  return Object.entries(variables ?? {}).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    template,
  );
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return saved === 'vi' ? 'vi' : 'en';
  });

  const setLanguage = (next: Language) => {
    localStorage.setItem('language', next);
    setLanguageState(next);
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      locale: language === 'vi' ? 'vi-VN' : 'en-US',
      setLanguage,
      toggleLanguage: () => setLanguage(language === 'en' ? 'vi' : 'en'),
      t: (text, variables) => translate(language, text, variables),
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage(): LanguageContextValue {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
